name: Docker

on:
  workflow_call:
    
jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: reff20
        password: ${{secrets.PW_DOCKERHUB}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: reff20/go_ci_alura:${{github.ref_name}}
